### PR TITLE
Show only called only methods in report

### PR DESCRIPTION
**Pull request by rmuslimov**

### CODE REVIEW

**Comment by cgewecke** [comment]
This is good! Just needs a rebase due to merging #52. If possible could you add this option to the test config [here](https://github.com/cgewecke/eth-gas-reporter/blob/master/mock/config-template.js)?

**Comment by cgewecke** [comment]
@rmuslimov Resolved conflict manually and merging. Thanks again :)

**Comment by rmuslimov** [comment]
@cgewecke Sorry that I didn't help. Were too busy this week. thanks!

**Comment by cgewecke** [comment]
@rmuslimov No worries! You've been incredibly helpful.

**Pull request merged**
