### PR TITLE
Remove unused request package

### PR DESCRIPTION
**Pull request by ChristopherDedominici**
It seems like that the request package is not used at all. It should be removed.

### CODE REVIEW

**Review by cgewecke — APPROVED** [review]
LGTM

**Comment by fvictorio** [comment]
@cgewecke thanks for merging this! Could you publish a new version of `eth-gas-reporter` with these changes?

**Comment by cgewecke** [comment]
@fvictorio Yes, just have one more thing to do here and will publish today. Promise.

**Comment by cgewecke** [comment]
Published with 0.2.26

**Comment by fvictorio** [comment]
Thanks!

**Pull request merged**
