### PR TITLE
fix methodID to consider the contractName

### PR DESCRIPTION
**Pull request by wighawag**
fix methodID to consider the contractName
Without it, the gas reporting is wring when 2 different contract have some of the same function signature

### CODE REVIEW

**Comment by wighawag** [comment]
this PR also skip non deployed contract (like base contract...) for the report
+ it now consider the gas used in truffle migrations

**Comment by wighawag** [comment]
I was going to create an issue and then found about https://github.com/cgewecke/eth-gas-reporter/pull/84

It says merged in master but looking at master, there does not seem to be the fixed included.

**Comment by cgewecke** [comment]
@wighawag It got reverted because it wasn't recording the gas values correctly and the tests got mangled so that wasn't apparent on merge. 

Thanks so much for the set of PRs you've opened! All great. 🙂  Reviewing them this morning.

**Comment by cgewecke** [comment]
Published in `0.1.11`

**Pull request merged**
