### PR TITLE
Update deprecated packages

### PR DESCRIPTION
**Pull request by ChristopherDedominici**
Update deprecated packages:
- ethers
- mocha

Remove deprecated packages:
- request
- request-promise-native

### CODE REVIEW

**Comment by cgewecke** [comment]
@ChristopherDedominici Sorry for a pre-emptive review ... I think this might be a bit tricky. The package is super old.

Maybe PR could be split into a few pieces 
+ make changes for newer ethers
+ do something about request
+ bump mocha

I'm happy to do the first three, would you like to just make this one a mocha bump?

**Comment by frangio** [comment]
See https://github.com/cgewecke/eth-gas-reporter/pull/295

**Comment by cgewecke** [comment]
@ChristopherDedominici If you *are* continuing with this it will be necessary to rebase against master to get the tests running. The repo was not working with more recent versions of Node.

@frangio Updated mocha in #295 (merged)

**Comment by ChristopherDedominici** [comment]
@cgewecke I split this PR into smaller ones:
- bump ethers version: [https://github.com/cgewecke/eth-gas-reporter/pull/296](https://github.com/cgewecke/eth-gas-reporter/pull/296)
- request: I'll take a look now

**Comment by cgewecke** [comment]
Closing via #299, #297, #296, #295

**Pull request closed without merging**
